-- DDL

CREATE DATABASE GUFI_TARDE;
GO

USE GUFI_TARDE;
GO

-- Tabelas para iniciar:
-- TIPOUSUARIO
CREATE TABLE TIPOUSUARIO (
	idTipoUsuario SMALLINT PRIMARY KEY IDENTITY(1,1),
	tituloTipoUsuario VARCHAR(50) UNIQUE NOT NULL
);
GO

--TIPOEVENTO
CREATE TABLE TIPOEVENTO (
	idTipoEvento INT PRIMARY KEY IDENTITY,
	tituloTipoEvento VARCHAR(100) UNIQUE NOT NULL
);
GO

CREATE TABLE SITUACAO (
	idSituacao TINYINT PRIMARY KEY IDENTITY,
	descricao VARCHAR(25) UNIQUE NOT NULL
);
GO

-- INSTITUICAO
CREATE TABLE INSTITUICAO (
	idInstituicao SMALLINT PRIMARY KEY IDENTITY,
	CNPJ CHAR(18) UNIQUE NOT NULL,
	nomeFantasia VARCHAR(100) NOT NULL,
	endereco VARCHAR(150) UNIQUE NOT NULL
);
GO

-- USUARIO
CREATE TABLE USUARIO (
	idUsuario INT PRIMARY KEY IDENTITY,
	idTipoUsuario SMALLINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario),
	nomeUsuario VARCHAR(100) NOT NULL,
	email VARCHAR(256) UNIQUE NOT NULL,
	senha VARCHAR(10) NOT NULL CHECK( len(senha) >= 8)
);
GO

-- EVENTO
CREATE TABLE EVENTO (
	idEvento INT PRIMARY KEY IDENTITY,
	idTipoEvento INT FOREIGN KEY REFERENCES TIPOEVENTO(idTipoEvento),
	idInstituicao SMALLINT FOREIGN KEY REFERENCES INSTITUICAO(idInstituicao),
	nomeEvento VARCHAR(50) NOT NULL,
	descricao VARCHAR(300) NOT NULL,
	dataEvento DATETIME NOT NULL,
	acessoLivre BIT DEFAULT (1)
);
GO

-- PRESENCA
CREATE TABLE PRESENCA (
	idPresenca INT PRIMARY KEY IDENTITY,
	idUsuario INT FOREIGN KEY REFERENCES USUARIO(idUsuario),
	idEvento INT FOREIGN KEY REFERENCES EVENTO(idEvento),
	idSituacao TINYINT FOREIGN KEY REFERENCES SITUACAO(idSituacao)
);
GO

/*
	RESUMO:
	PRIMARY KEY = CHAVE PRIMÁRIA;
	FOREIGN KEY = CHAVE ESTRANGEIRA;
	IDENTITY = DEFINE QUE O CAMPO SERÁ AUTO-INCREMENTADO E ÚNICO;
	NOT NULL = DEFINE QUE NÃO PODE SER NULO, OU SEJA, OBRIGATÓRIO;
	UNIQUE = DEFINE QUE O VALOR DO CAMPO SERÁ ÚNICO, OU SEJA, NÃO SE REPETE;
	DEFAULT = DEFINE UM VALOR PADRÃO, CASO NENHUM SEJA INFORMADO;
	GO = PAUSA A LEITURA E EXECUTA O BLOCO DE CÓDIGO ACIMA.
*/